public with sharing class q6 implements Database.Batchable<SObject>, Database.RaisesPlatformEvents {

    public Database.QueryLocator start(Database.BatchableContext context) {
        // TODO: add a WHERE clause to filter records
        return Database.getQueryLocator([SELECT Id FROM SObject]);
    }

    public void execute(Database.BatchableContext context, List<SObject> scope) {

    }

    public void finish(Database.BatchableContext context) {

    }
}
